# 📦 Required Imports
import os
import json
from fpdf import FPDF
from datetime import datetime

# 📁 Paths
PREDICTED_SYNTHETIC_LABELS_PATH = "outputs/predicted_synthetic_labels.json"
OUTPUT_DIR = "outputs/generated_reports_synthetic"
FONT_PATH = "fonts/Arial.ttf"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# 📜 PDF Class
class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.add_font("ArialUnicode", "", FONT_PATH, uni=True)

    def header(self):
        self.set_font("ArialUnicode", "", 14)
        self.cell(0, 10, "Brain MRI Diagnostic Report (Synthetic)", ln=True, align="C")
        self.ln(5)

    def chapter_title(self, title):
        self.set_font("ArialUnicode", "", 13)
        self.cell(0, 10, title, ln=True)
        self.ln(2)

    def chapter_body(self, text):
        self.set_font("ArialUnicode", "", 12)
        self.multi_cell(0, 8, text)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("ArialUnicode", "", 8)
        self.cell(0, 10, "Generated by AI Assistant", align="C")

# 📄 Load predictions
def load_predictions(path):
    with open(path, "r") as f:
        return json.load(f)

# 📄 Generate PDF for each synthetic patient
def generate_pdf(prediction_info, idx):
    pdf = PDF()
    pdf.add_page()

    now = datetime.now().strftime("%d %B %Y - %H:%M")

    # General Info
    pdf.chapter_title("General Information")
    pdf.set_font("ArialUnicode", "", 12)
    pdf.cell(0, 10, f"Date & Time: {now}", ln=True)
    pdf.cell(0, 10, f"Patient ID: {prediction_info.get('patient_id', 'N/A')}", ln=True)
    pdf.cell(0, 10, f"Source: Synthetic Patient Data", ln=True)
    pdf.ln(5)

    # Model Prediction
    pdf.chapter_title("Model Prediction")
    predicted_class = prediction_info.get("predicted_class", "Unknown")
    confidence = prediction_info.get("confidence", 0.0)
    pdf.set_font("ArialUnicode", "", 12)
    pdf.cell(0, 10, f"Predicted Tumor Type: {predicted_class}", ln=True)
    pdf.cell(0, 10, f"Confidence: {confidence}%", ln=True)

    if confidence < 60:
        pdf.ln(3)
        pdf.set_text_color(255, 0, 0)
        pdf.multi_cell(0, 10, "⚠️ Warning:\nThe model's confidence is low. Please review this case manually.")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # Dummy Report
    pdf.chapter_title("Report Details")
    pdf.chapter_body("This is a synthetic MRI report generated for training purposes. No real medical data is associated with this record.")

    # Conclusion
    pdf.chapter_title("Conclusion")
    pdf.chapter_body("Synthetic data conclusion based on model prediction.")

    # Recommendations
    pdf.chapter_title("Recommendations")
    pdf.chapter_body("No medical action required. For training only.")

    # Save PDF
    output_path = os.path.join(OUTPUT_DIR, f"synthetic_report_{idx}.pdf")
    pdf.output(output_path)

    print(f"✅ Saved: {output_path}")

# 🚀 Main
def main():
    predictions = load_predictions(PREDICTED_SYNTHETIC_LABELS_PATH)

    print(f"✅ Loaded {len(predictions)} synthetic predictions.")

    for idx, prediction_info in enumerate(predictions, start=1):
        generate_pdf(prediction_info, idx)

if __name__ == "__main__":
    main()