# 📦 Required Imports
from fpdf import FPDF
from datetime import datetime
import os

# 📄 Example Patient Data (Buraya prediction verisini de ekledik)
patient_data = {
    "age": "74",
    "sex": "Female",
    "race": "Caucasian",
    "year": "2023",
    "report": "A series of T1- and T2-weighted MR tomograms in three planes visualized sub- and supratentorial structures. [...]",
    "conclusion": "Single /2/ focal masses in the right frontal and parietal lobes with a zone of perifocal vasogenic edema. [...]",
    "recommendations": "Oncology consultation.",
    "predicted_tumor_type": "Meningioma",  # 👈 Modelin tahmini sınıfı
    "confidence": 97.16                    # 👈 Modelin tahmin güveni
}

# 📁 Ensure output directory exists
os.makedirs("outputs/generated_reports", exist_ok=True)

# 📜 PDF Class
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, "Brain MRI Diagnostic Report", ln=True, align="C")
        self.ln(5)

    def chapter_title(self, title):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, title, ln=True)
        self.ln(2)

    def chapter_body(self, text):
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 8, text)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by AI Assistant", align="C")

# 🖨️ Create PDF
pdf = PDF()
pdf.add_font("Arial", "", "fonts/Arial.ttf", uni=True)  # Fontu ekledik
pdf.set_font("Arial", "", 12)
pdf.add_page()

now = datetime.now().strftime("%d %B %Y - %H:%M")

# Header bilgileri
pdf.cell(0, 10, f"Date & Time: {now}", ln=True)
pdf.cell(0, 10, f"Patient Age: {patient_data['age']}", ln=True)
pdf.cell(0, 10, f"Patient Sex: {patient_data['sex']}", ln=True)
pdf.cell(0, 10, f"Patient Race: {patient_data['race']}", ln=True)
pdf.cell(0, 10, f"Year of Study: {patient_data['year']}", ln=True)
pdf.ln(5)

# 🧠 Model Prediction bilgisi (YENİ EK)
pdf.chapter_title("Model Prediction")
pdf.chapter_body(
    f"Predicted Tumor Type: {patient_data['predicted_tumor_type']}\n"
    f"Confidence: {patient_data['confidence']:.2f}%"
)

# Report Sections
pdf.chapter_title("Report Details")
pdf.chapter_body(patient_data["report"])

pdf.chapter_title("Conclusion")
pdf.chapter_body(patient_data["conclusion"])

pdf.chapter_title("Recommendations")
pdf.chapter_body(patient_data["recommendations"])

# Save
output_path = "outputs/generated_reports/generated_report_with_prediction.pdf"
pdf.output(output_path)

print(f"✅ PDF Report saved successfully at {output_path}")
